
service: aws-factory

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
custom:
  FACTORY_BUS: ${file(./config.${opt:stage, self:provider.stage, 'dev'}.json):FACTORY_BUS}

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

  environment:
    FACTORY_BUS: ${self:custom.FACTORY_BUS}
    FACTORY_EVENT_SOURCE: ${file(./config.${opt:stage, self:provider.stage, 'dev'}.json):FACTORY_EVENT_SOURCE}
#  iamRoleStatements:

package:
  exclude:
    - venv/**

functions:
  receiver:
    handler: workers/receiver/handler.receiver
    events:
     - httpApi:
         path: /factory/aws/accounts
         method: post

  accountCreate:
    handler: workers/account_request/handler.event_handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - "organizations:TagResource"
          - "organizations:ListAccounts"
          - "organizations:DescribeAccount"
          - "ec2:DescribeAccountAttributes"
          - "organizations:CreateAccount"
          - "events:*"
        Resource: "*"
    environment:
      ALLOW_BILLING_ACCESS: ${file(./config.${opt:stage, self:provider.stage, 'false'}.json):ALLOW_BILLING_ACCESS}
    events:
      - eventBridge:
          eventBus: ${self:custom.FACTORY_BUS}
          pattern:
            source:
              - factory.requests.newAccountRequest

  deleteVpc:
    handler: workers/delete_vpc/handler.lambda_handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - "ec2:*"
        Resource: "*"
    events:
      - eventBridge:
          eventBus: ${self:custom.FACTORY_BUS}
          pattern:
            source:
              - factory.accounts.accountCreated
              
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

